apiVersion: v1
kind: Service
metadata:
  name: video-upload-service
  labels:
    app: video-upload-service
spec:
  selector:
    app: video-upload-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP # Internal service. Use Ingress for external exposure.
